"system_name": "SmartScraper_LangGraph_System"
"description": "Sistema inteligente para análisis de estructura web y extracción de reglas de scraping"
custom_settings:
  DEFAULT_REQUEST_HEADERS:
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Accept-Language: en-US,en;q=0.9
    Accept-Encoding: gzip, deflate, br
    Connection: keep-alive
    Upgrade-Insecure-Requests: "1"
    Sec-Fetch-Dest: document
    Sec-Fetch-Mode: navigate
    Sec-Fetch-Site: none
    Cache-Control: max-age=0

  #speed control
  RANDOMIZE_DOWNLOAD_DELAY: 1
  CONCURRENT_REQUESTS: 1
  CONCURRENT_REQUESTS_PER_DOMAIN: 1

  # Autothrottle
  AUTOTHROTTLE_ENABLED: true
  AUTOTHROTTLE_START_DELAY: 5
  AUTOTHROTTLE_MAX_DELAY: 20
  AUTOTHROTTLE_TARGET_CONCURRENCY: 0.5

  #Limits and time outs
  DOWNLOAD_TIMEOUT: 30
  RETRY_TIMES: 2
  RETRY_HTTP_CODES:
    - 500
    - 502
    - 503
    - 504
    - 522
    - 524
    - 408
    - 429
    - 403

  # allow cookies
  COOKIES_ENABLED: true

realistic_user_agents:
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0"
